In [117]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

1.0.1


# Let's Start

## Working with scalars


### PyTorch tensors are created using torch.tensors() 
#### Source : https://pytorch.org/docs/stable/torch.html

In [118]:
#defining tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [119]:
# Get dimention of the tensor 
scalar.dim()

0

In [120]:
# Get tensor back as Python int
scalar.item()

7

In [121]:
# working with vector
vector = torch.tensor([7,7])

In [122]:
vector.shape

torch.Size([2])

In [123]:
# Working with MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,6]])
MATRIX

tensor([[7, 8],
        [9, 6]])

In [124]:
MATRIX[1]

tensor([9, 6])

In [125]:
MATRIX[0]

tensor([7, 8])

In [126]:
MATRIX.shape

torch.Size([2, 2])

In [127]:
# working with tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [128]:
TENSOR.shape

torch.Size([1, 3, 3])

In [129]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random Tensor

Why random tensors?

Random tensors are important because the way manu nn learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random number -> look at data -> update random numbers -> look at data -> update random numbers `

In [130]:
# creating a random tensors with pytorch of size (3,4)

random_tesnor = torch.rand(3,4)
random_tesnor

tensor([[0.9817, 0.6837, 0.2299, 0.7905],
        [0.1798, 0.2871, 0.0182, 0.1596],
        [0.4767, 0.2844, 0.2997, 0.1513]])

In [131]:
random_tesnor = torch.rand(1,3,4)
random_tesnor

tensor([[[0.2628, 0.8778, 0.2172, 0.9035],
         [0.3048, 0.3532, 0.1555, 0.5794],
         [0.2098, 0.8995, 0.7801, 0.6417]]])

In [132]:
random_tesnor = torch.rand(2,3,4)
random_tesnor

tensor([[[0.9904, 0.5302, 0.9343, 0.3158],
         [0.4418, 0.6684, 0.1749, 0.0678],
         [0.1787, 0.7009, 0.1838, 0.4748]],

        [[0.5795, 0.0560, 0.7371, 0.1682],
         [0.4597, 0.6477, 0.1224, 0.0895],
         [0.6942, 0.4728, 0.3102, 0.2842]]])

In [133]:
random_image_size_tensor = torch.rand(size = (224,224,3)) #height width and color channel
random_image_size_tensor.shape

torch.Size([224, 224, 3])

## Zeroes and One

In [134]:
zero = torch.zeros(size = (3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [135]:
random_tensor = torch.rand(size = (3,4))

In [136]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [137]:
random_tensor*zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [138]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [139]:
ones.dtype

torch.float32

## Creating range of Tensors and Tensor like 

### arange()

In [140]:
torch.range(0,10) # deprecated

/home/harshal/anaconda3/envs/myenv/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [141]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
torch.arange(start = 0, end =1000, step = 77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [143]:
one_to_ten = torch.arange(start =1, end =11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### tensors-like()

In [144]:
#input is another tensor that we want to make an instance of 

ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [145]:
ten_zeros = torch.ones_like(input = one_to_ten)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

**Note:** Tensors datatypes is one of the big errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [146]:
# Float 32 tensor

float_32_tensor = torch.tensor([3,6,9], dtype = None)
float_32_tensor

tensor([3, 6, 9])

In [147]:
float_32_tensor.dtype

torch.int64

In [148]:
float_32_tensor = torch.tensor([3.,6.,9.], dtype = None)
float_32_tensor

tensor([3., 6., 9.])

In [149]:
float_32_tensor.dtype # default data type

torch.float32

In [150]:
float_32_tensor = torch.tensor([3.,6.,9.],
                               dtype = None,
                               device = None,
                               requires_grad = False )
float_32_tensor

tensor([3., 6., 9.])

In [151]:
float16_tensor = float_32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [152]:
float16_tensor*float_32_tensor

RuntimeError: expected type torch.FloatTensor but got torch.HalfTensor

In [159]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [160]:
float_32_tensor* int_32_tensor

RuntimeError: expected type torch.FloatTensor but got torch.IntTensor

In [161]:
int_32_tensor * float_32_tensor

RuntimeError: expected type torch.FloatTensor but got torch.IntTensor

### Getting information from tensor

1. Tensors not right datatype -  to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape froma tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [162]:
# create a tensor 

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5609, 0.0926, 0.9079, 0.0045],
        [0.1853, 0.1727, 0.5160, 0.5687],
        [0.0970, 0.2538, 0.2292, 0.2324]])

In [163]:
# Find out details about the tensor

print(some_tensor)

print("Data type of tensor: ",some_tensor.dtype )
print("Shape of the tensor: ",some_tensor.shape)
print("Device the tensor is on: ", some_tensor.device)
print("Gradient value of the tensor: ", some_tensor.requires_grad)

tensor([[0.5609, 0.0926, 0.9079, 0.0045],
        [0.1853, 0.1727, 0.5160, 0.5687],
        [0.0970, 0.2538, 0.2292, 0.2324]])
Data type of tensor:  torch.float32
Shape of the tensor:  torch.Size([3, 4])
Device the tensor is on:  cpu
Gradient value of the tensor:  False


### Manipulating Tensors

Tensor operations include:
* Addition
* Substraction
* Multiplication ( element wise )
* Division
* Matrix Multiplication

In [164]:
# creating a Tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [165]:
tensor * 10

tensor([10, 20, 30])

In [166]:
tensor - 10

tensor([-9, -8, -7])

In [167]:
# PyTorch inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [168]:
torch.add(tensor,10)

tensor([11, 12, 13])

###  Matrix multiplication

Two main ways of performing multiplication in nn and dl 

1. Element-wise multiplication
2. Matrix Multiplication ( dot product )

There are two main rules that performing matrix multiplicatio needs to be satisfied:
1. The **inner dimentions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` would work
* `(3,2) @ (2,3)` would work
2. The resulting matrix have the shape of the outer dimention
* `(2,3) @ (3,2)` the resulting shape is `(2,2)`
* `(3,2) @ (2,3) -> (3,3)`

In [169]:
# Element wise 

print(tensor,"*", tensor)
print("Equals: ", tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


In [170]:
# Matrix Multiplication
# this will give a dot product of itself with itself
torch.matmul(tensor,tensor)

tensor(14)

In [172]:
%%time

value = 0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
    
print(value)


tensor(14)
CPU times: user 0 ns, sys: 3.49 ms, total: 3.49 ms
Wall time: 2.15 ms


In [173]:
%%time 

torch.matmul(tensor, tensor)

CPU times: user 748 µs, sys: 97 µs, total: 845 µs
Wall time: 676 µs


tensor(14)

### One of the most common error in deep learning is Shape Error

Fun: www.matrixmultiplication.xyz

In [174]:
# shapes for matrix multiplication
tensor_A =  torch.tensor([[1,2],
                           [3,4],
                           [5,6]])
    
tensor_B = torch.tensor([[7,10],
                        [11,12],
                        [12,10]])

In [193]:
#torch.mm(tensor_A,tensor_B) is same as torch.matmul (it's an alias)
torch.matmul(tensor_A,tensor_B)

RuntimeError: size mismatch, m1: [3 x 2], m2: [3 x 2] at /opt/conda/conda-bld/pytorch_1550813258230/work/aten/src/TH/generic/THTensorMath.cpp:940

In [179]:
torch.mm(tensor_A,tensor_B)

RuntimeError: size mismatch, m1: [3 x 2], m2: [3 x 2] at /opt/conda/conda-bld/pytorch_1550813258230/work/aten/src/TH/generic/THTensorMath.cpp:940

In [180]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

 To fix out the tensor shape issue, we can manipulate the shape of one of our tensor using **transpose**.
 
 A **transpose** switches the axes or dimention of a given tensor

In [184]:
tensor_B.t()

tensor([[ 7, 11, 12],
        [10, 12, 10]])

In [191]:
# Shape of the transposed
tensor_B.t().shape

torch.Size([2, 3])

In [192]:
# Shape of the original
tensor_B.shape

torch.Size([3, 2])

In [197]:
output = torch.matmul(tensor_A, tensor_B.t())
output, output.shape

(tensor([[ 27,  35,  32],
         [ 61,  81,  76],
         [ 95, 127, 120]]),
 torch.Size([3, 3]))

###  Tensor Aggregation
1. Min
2. Max
3. Mean
4. Sum, etc..


In [214]:
#create tensor
x = torch.arange(2,112,9)
x, x.dtype

(tensor([  2,  11,  20,  29,  38,  47,  56,  65,  74,  83,  92, 101, 110]),
 torch.int64)

In [202]:
# Find the min
torch.min(x), x.min()

(tensor(2), tensor(2))

In [203]:
# Find the max
torch.max(x), x.max()

(tensor(110), tensor(110))

In [205]:
# Find the mean
torch.mean(x), x.mean()

RuntimeError: Can only calculate the mean of floating types. Got Long instead.

In [217]:
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(56.), tensor(56.))

In [218]:
# Find the sum

torch.sum(x), x.sum()

(tensor(728), tensor(728))

### Finding the positional min and max ie. `argmax` and `argmin`

In [219]:
x

tensor([  2,  11,  20,  29,  38,  47,  56,  65,  74,  83,  92, 101, 110])

In [221]:
# Find the position in the tensor that has the minimum value with argmin() -> returns index of the minimum value
x.argmin()

tensor(0)

In [222]:
# Find the position in the tensor that has the maximum value with argmin() -> returns index of the minimum value
x.argmax()

tensor(12)

### Reshape, squeezing, unsqueezing and Stacking Tensors 

* `Reshape` : Reshape a input tebsor to a defined shape
* `View` : Retuen a view of an input tensor of a certain shape but keep the same memory as the original tensor
* `Stacking` : Combine multiple tensor on the top of each other `(vstack)` or side by side `(hstack)`
* Squeeze : Removes all `1` dimention from a tensor
* Unsqueeze : Add a `1` dimention to a target tensor
* Permute : Return a view of the input with dimentions permutted `(swapped)` in a certain way 

In [224]:
x, x.shape

(tensor([  2,  11,  20,  29,  38,  47,  56,  65,  74,  83,  92, 101, 110]),
 torch.Size([13]))

In [229]:
# Add an extra dimention

x_reshaped = x.reshape(13,1)
x_reshaped, x_reshaped.shape

(tensor([[  2],
         [ 11],
         [ 20],
         [ 29],
         [ 38],
         [ 47],
         [ 56],
         [ 65],
         [ 74],
         [ 83],
         [ 92],
         [101],
         [110]]),
 torch.Size([13, 1]))

In [232]:
x = torch.arange(1,13)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [238]:
x_reshaped = x.reshape(3,4)
x_reshaped, x_reshaped.size() , x_reshaped.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]),
 torch.Size([3, 4]))

In [239]:
x_reshaped = x.reshape(6,2)
x_reshaped, x_reshaped.size() , x_reshaped.shape

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([6, 2]),
 torch.Size([6, 2]))

In [240]:
x_reshaped = x.reshape(2,6)
x_reshaped, x_reshaped.size() , x_reshaped.shape

(tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]),
 torch.Size([2, 6]),
 torch.Size([2, 6]))

In [241]:
x_reshaped = x.reshape(3,2,2)
x_reshaped, x_reshaped.size() , x_reshaped.shape

(tensor([[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]],
 
         [[ 9, 10],
          [11, 12]]]),
 torch.Size([3, 2, 2]),
 torch.Size([3, 2, 2]))

In [244]:
# Change of view

z = x.view(1,12)
z, z.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 torch.Size([1, 12]))

`Changing z changes x` ( because a view of a tensor shares the same memory as the original input )

In [247]:
z[:,0] = 5

z,x

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

### *Stack the tensor on top of each other* 

In [248]:
x

tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [250]:
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [251]:
x_stacked = torch.stack([x,x,x,x], dim =1)
x_stacked

tensor([[ 5,  5,  5,  5],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10],
        [11, 11, 11, 11],
        [12, 12, 12, 12]])

#### Squeeze : Removes all the single dimention from a target tensor

In [252]:
x_reshaped

tensor([[[ 5,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [253]:
x_reshaped.shape

torch.Size([3, 2, 2])

In [258]:
x_reshaped = x_reshaped.reshape(4,3,1)
x_reshaped, x_reshaped.shape

(tensor([[[ 5],
          [ 2],
          [ 3]],
 
         [[ 4],
          [ 5],
          [ 6]],
 
         [[ 7],
          [ 8],
          [ 9]],
 
         [[10],
          [11],
          [12]]]),
 torch.Size([4, 3, 1]))

In [263]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([[ 5,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([4, 3]))

In [264]:
x_squeezed = x_reshaped.squeeze()

#### Unsqueeze : Adds a single dimention from a target tensor

In [270]:
print('Previous Squeezed version: ', x_squeezed)
print('\nPrevious Squeezed version shape: ', x_squeezed.shape)

x_unsqueezed = x_squeezed.unsqueeze(dim = 0)

print('\nUnsqueezed version added to 0 dimention: ', x_unsqueezed)
print('\nUnsqueezed version added to 0 dimention shape: ', x_unsqueezed.shape)

x_unsqueezed = x_squeezed.unsqueeze(dim = 1)

print('\nUnsqueezed version added to 1 dimention: ', x_unsqueezed)
print('\nUnsqueezed version added to 1 dimention shape: ', x_unsqueezed.shape)

Previous Squeezed version:  tensor([[ 5,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Previous Squeezed version shape:  torch.Size([4, 3])

Unsqueezed version added to 0 dimention:  tensor([[[ 5,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

Unsqueezed version added to 0 dimention shape:  torch.Size([1, 4, 3])

Unsqueezed version added to 1 dimention:  tensor([[[ 5,  2,  3]],

        [[ 4,  5,  6]],

        [[ 7,  8,  9]],

        [[10, 11, 12]]])

Unsqueezed version added to 1 dimention shape:  torch.Size([4, 1, 3])


 ####  `torch.permute` - rearranges the dimention of a target tensor in a specified order

In [272]:
x_original = torch.rand(size = (224,224,3)) # Height, Width and color channel

In [274]:
# Permute the original tensor to rearrange the axis (or dim) order

x_permuted = x_original.permute(2,0,1) # shifts axis 0->1 , 1->2,2->0

print('Previous shape: ', x_original.shape)
print('New shape: ', x_permuted.shape)

Previous shape:  torch.Size([224, 224, 3])
New shape:  torch.Size([3, 224, 224])
